name: Run pipeline and build Docker image

on:
  push:
    branches:
      - main  # Change this if needed ok

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          if [ -f load_prediction/requirements.txt ]; then
            pip install -r load_prediction/requirements.txt
          else
            echo "requirements.txt not found!" && exit 1
          fi

      - name: Run pipeline.py
        run: python load_prediction/pipeline.py

  build-docker-image:
    needs: run-pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t my-app:latest load_prediction/

      - name: Check for changes
        run: |
          git status
          if ! git diff --quiet; then
            git config --global user.name "${{ secrets.GH_USERNAME }}"
            git config --global user.email "${{ secrets.GH_EMAIL }}"
            git add .
            git commit -m "Automated commit"
            git push https://${{ secrets.GH_USERNAME }}:${{ secrets.GH_PAT }}@github.loan-prediction.git HEAD:main
          else
            echo "No changes to commit"
