name: Run Pipeline and Push Docker Image to Dockerhub

on:
  push:
    branches:
      - main

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Pipeline
        run: python pipeline.py

  build-and-push-docker:
    runs-on: ubuntu-latest
    needs: run-pipeline   # Ensure pipeline runs successfully before building Docker image

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/loan-prediction:latest .

      - name: Push Docker Image to DockerHub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/loan-prediction:latest
  

  deploy-to-lightsail:
    runs-on: ubuntu-latest
    needs: build-and-push-docker  # Ensure Docker image is pushed before deploying

    steps:
      - name: Deploy to AWS Lightsail
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key: ${{ secrets.LIGHTSAIL_SSH_PRIVATE_KEY }}
          script: |
            # Stop and remove any existing container (if running)
            docker stop loan-prediction || true
            docker rm loan-prediction || true

            # Free port 8000 if occupied
            sudo fuser -k 8000/tcp || true

            # Remove old image
            docker images -q ${{ secrets.DOCKERHUB_USERNAME }}/loan-prediction | xargs docker rmi || true

            # Pull the latest Docker image
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/loan-prediction:latest
            
            # Run the new container
            docker run -d --restart=always --name loan-prediction -p 8000:8000 ${{ secrets.DOCKERHUB_USERNAME }}/loan-prediction:latest